# Generated by Django 5.2.9 on 2025-12-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fund_type', models.CharField(choices=[('RESTRICTED', 'Restricted (Zakat, Sadaqah)'), ('OPERATIONAL', 'Operational (General Fund)')], default='OPERATIONAL', max_length=20)),
                ('source', models.CharField(choices=[('LOCAL', 'Local'), ('FCRA', 'FCRA (Foreign Contribution)')], default='LOCAL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_expense', models.BooleanField(default=True)),
                ('donor_pan', models.CharField(blank=True, help_text='Mandatory for donations > 2000', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('audit_status', models.CharField(choices=[('PENDING', 'Pending Audit'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('ERROR', 'Audit Error')], default='PENDING', max_length=20)),
                ('audit_notes', models.TextField(blank=True, help_text='AI Analysis Reasoning', null=True)),
                ('fund_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fundcategory')),
            ],
        ),
    ]
