# Generated by Django 5.2.9 on 2025-12-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('jamath', '0002_survey_household_custom_data_member_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jamath.household'),
        ),
    ]
