# Generated by Django 5.2.9 on 2026-03-17 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(default='admin@localhost.com', max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('allow_manual_ledger', models.BooleanField(default=False, help_text='Allow this Mosque to use Manual Ledger (Advanced Finance Mode)')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DigitalJamath', max_length=100)),
                ('openrouter_api_key', models.CharField(blank=True, help_text='API Key for Basira AI (OpenRouter)', max_length=255, null=True)),
                ('brevo_api_key', models.CharField(blank=True, help_text='API Key for Brevo SMTP', max_length=255, null=True)),
                ('brevo_email_sender', models.EmailField(default='noreply@project-mizan.com', help_text='Default sender email address', max_length=254)),
                ('enable_registration', models.BooleanField(default=True, help_text='Allow new workspaces to register')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (only admins can login)')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
