# Generated by Django 5.2.9 on 2025-12-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_email',
            field=models.EmailField(default='admin@localhost.com', max_length=254),
        ),
    ]
