# Generated by Django 5.2.9 on 2026-02-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_manual_ledger',
            field=models.BooleanField(default=False, help_text='Allow this tenant to use Manual Ledger (Advanced Finance Mode)'),
        ),
    ]
