# Generated by Django 5.2.9 on 2026-02-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_client_allow_manual_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='setup_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('CUSTOM', 'Custom')], default='STANDARD', max_length=20),
        ),
    ]
