# Generated by Django 5.2.9 on 2026-03-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SCORING', 'Scoring'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='APPLIED', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('skills', models.JSONField(default=list, help_text="List of skills e.g. ['Medical', 'Driving']")),
                ('is_available', models.BooleanField(default=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
