# Generated by Django 5.2.9 on 2025-12-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('economic_status', models.CharField(choices=[('ZAKAT_ELIGIBLE', 'Zakat Eligible'), ('SOLVENT', 'Solvent'), ('WEALTHY', 'Wealthy')], max_length=20)),
                ('zakat_score', models.IntegerField(default=0, help_text='AI Calculated score 0-100')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_head_of_family', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='jamath.household')),
            ],
        ),
    ]
