# Generated by Django 5.2.9 on 2026-03-17 10:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('economic_status', models.CharField(choices=[('ZAKAT_ELIGIBLE', 'Zakat Eligible'), ('AAM', 'Aam / Sahib-e-Nisab')], default='AAM', max_length=20)),
                ('housing_status', models.CharField(choices=[('OWN', 'Own House'), ('RENTED', 'Rented'), ('FAMILY', 'Family Property')], default='OWN', max_length=20)),
                ('zakat_score', models.IntegerField(default=0, help_text='AI Calculated score 0-100')),
                ('membership_id', models.CharField(blank=True, help_text='Jamath Membership ID (e.g., JM-001)', max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact for OTP login', max_length=15, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-verified household')),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Ad-hoc fields like Village, Blood Group')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('target_household', models.ForeignKey(blank=True, help_text='If set, this announcement is visible ONLY to this household.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='jamath.household')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(help_text='e.g., RCP-2025-001', max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('RECEIPT', 'Receipt Voucher'), ('PAYMENT', 'Payment Voucher'), ('JOURNAL', 'Journal Entry')], max_length=20)),
                ('date', models.DateField()),
                ('narration', models.TextField(help_text='Description of the transaction')),
                ('donor_name_manual', models.CharField(blank=True, help_text='For guest donors', max_length=200)),
                ('donor_pan', models.CharField(blank=True, help_text='Required for amounts > ₹2000', max_length=10)),
                ('donor_intent', models.TextField(blank=True, help_text="Specific direction like 'For buying fans only'")),
                ('vendor_invoice_no', models.CharField(blank=True, max_length=50)),
                ('vendor_invoice_date', models.DateField(blank=True, null=True)),
                ('proof_document', models.FileField(blank=True, help_text='Required for amounts > ₹500', null=True, upload_to='vouchers/proofs/')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('NEFT', 'Bank Transfer (NEFT/IMPS)'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('is_finalized', models.BooleanField(default=False, help_text='Locked entries cannot be modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., 1001, 2001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity/Corpus')], max_length=20)),
                ('fund_type', models.CharField(blank=True, choices=[('ZAKAT', 'Restricted - Zakat'), ('SADAQAH', 'Restricted - Sadaqah'), ('CONSTRUCTION', 'Restricted - Construction'), ('GENERAL', 'Unrestricted - General')], help_text='Required for Income/Expense accounts', max_length=20, null=True)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jamath.ledger')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('particulars', models.CharField(blank=True, help_text='Additional line description', max_length=200)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jamath.journalentry')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='jamath.ledger')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('is_head_of_family', models.BooleanField(default=False)),
                ('relationship_to_head', models.CharField(choices=[('SELF', 'Self (Head)'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], default='SELF', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=15)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, help_text='e.g., 10th Pass, Graduate, Hafiz', max_length=100, null=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=255, null=True)),
                ('is_employed', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.TextField(blank=True, help_text='e.g., Needs Dialysis Support, Wheelchair', null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True, help_text='False = Pending admin approval')),
                ('occupation_details', models.TextField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='jamath.household')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='For Receipt vouchers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='jamath.member'),
        ),
        migrations.CreateModel(
            name='MembershipConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('ANNUAL', 'Annual'), ('BI_YEARLY', 'Bi-Yearly (6 months)'), ('MONTHLY', 'Monthly')], default='ANNUAL', max_length=20)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('payment_gateway_provider', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CASHFREE', 'Cashfree Payments'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=50)),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=50)),
                ('cashfree_app_id', models.CharField(blank=True, default='', max_length=100)),
                ('cashfree_secret_key', models.CharField(blank=True, default='', max_length=100)),
                ('organization_name', models.CharField(default='Digital Jamath', help_text='Legal Name for Receipts', max_length=200)),
                ('organization_address', models.TextField(blank=True, help_text='Registered Address')),
                ('organization_pan', models.CharField(blank=True, help_text='Organization PAN', max_length=20)),
                ('registration_number_80g', models.CharField(blank=True, help_text='80G Registration Number', max_length=100)),
                ('membership_id_prefix', models.CharField(default='JM-', help_text='Prefix for auto-generated membership IDs', max_length=10)),
                ('household_label', models.CharField(default='Gharane', help_text='Display label for households (e.g., Gharane, Families, Khandan)', max_length=50)),
                ('member_label', models.CharField(default='Afrad', help_text='Display label for members (e.g., Afrad, Members)', max_length=50)),
                ('masjid_name', models.CharField(blank=True, default='', help_text='Display name for the masjid', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'verbose_name': 'Membership Configuration',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('NIKAAH_NAMA', 'Nikaah Nama'), ('DEATH_CERT', 'Death Certificate'), ('NOC', 'Mahal Transfer NOC'), ('CHARACTER_CERT', 'Character Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the request', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='jamath.household')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text="Module-level permissions, e.g., {'finance': 'admin'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text="Official title, e.g. 'General Secretary'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Override role permissions if set')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='jamath.staffrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('minimum_required', models.DecimalField(decimal_places=2, help_text='Copied from config at creation', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending (Partial Payment)'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='jamath.household')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membership_portion', models.DecimalField(decimal_places=2, help_text='Amount towards membership fee', max_digits=10)),
                ('donation_portion', models.DecimalField(decimal_places=2, help_text='Voluntary extra as Sadaqah', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('donor_pan', models.CharField(blank=True, help_text='For 80G Compliance', max_length=15, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='jamath.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='For Payment vouchers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='jamath.supplier'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=list, help_text='Form Builder Schema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_surveys', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='jamath.household')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='jamath.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAgentChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='shared.mosque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'is_cleared', 'timestamp'], name='jamath_data_user_id_dad447_idx')],
            },
        ),
    ]
