# Generated by Django 5.2.9 on 2026-03-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='code',
            field=models.CharField(help_text='e.g., 1001, 2001', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('mosque', 'code')},
        ),
    ]
