# Generated by Django 5.2.9 on 2025-12-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0002_survey_household_custom_data_member_custom_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='membership_id',
            field=models.CharField(blank=True, help_text='Manual Jamath Membership ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='household',
            name='economic_status',
            field=models.CharField(choices=[('ZAKAT_ELIGIBLE', 'Zakat Eligible'), ('SOLVENT', 'Solvent'), ('WEALTHY', 'Wealthy')], default='SOLVENT', max_length=20),
        ),
    ]
