# Generated by Django 5.2.9 on 2026-04-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0002_alter_ledger_code_alter_ledger_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='fundraising_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target amount if this is a fundraiser', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional thumbnail or poster image', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_fundraiser',
            field=models.BooleanField(default=False, help_text='Flags this announcement as a fundraising campaign'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible to the general public outside the member portal'),
        ),
    ]
