# Generated by Django 5.2.9 on 2025-12-28 08:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0003_household_created_at_household_membership_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("BI_YEARLY", "Bi-Yearly (6 months)"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1200.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership Configuration",
            },
        ),
        migrations.AddField(
            model_name="household",
            name="housing_status",
            field=models.CharField(
                choices=[
                    ("OWN", "Own House"),
                    ("RENTED", "Rented"),
                    ("FAMILY", "Family Property"),
                ],
                default="OWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Admin-verified household"
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact for OTP login",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="education",
            field=models.CharField(
                blank=True,
                help_text="e.g., 10th Pass, Graduate, Hafiz",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="False = Pending admin approval"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_employed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single"),
                    ("MARRIED", "Married"),
                    ("WIDOWED", "Widowed"),
                    ("DIVORCED", "Divorced"),
                ],
                default="SINGLE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="relationship_to_head",
            field=models.CharField(
                choices=[
                    ("SELF", "Self (Head)"),
                    ("SPOUSE", "Spouse"),
                    ("SON", "Son"),
                    ("DAUGHTER", "Daughter"),
                    ("PARENT", "Parent"),
                    ("SIBLING", "Sibling"),
                    ("OTHER", "Other"),
                ],
                default="SELF",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="requirements",
            field=models.TextField(
                blank=True,
                help_text="e.g., Needs Dialysis Support, Wheelchair",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="skills",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated skills",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="economic_status",
            field=models.CharField(
                choices=[
                    ("ZAKAT_ELIGIBLE", "Zakat Eligible"),
                    ("AAM", "Aam / Sahib-e-Nisab"),
                ],
                default="AAM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="membership_id",
            field=models.CharField(
                blank=True,
                help_text="Jamath Membership ID (e.g., JM-001)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("NIKAAH_NAMA", "Nikaah Nama"),
                            ("DEATH_CERT", "Death Certificate"),
                            ("NOC", "Mahal Transfer NOC"),
                            ("CHARACTER_CERT", "Character Certificate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="jamath.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "minimum_required",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Copied from config at creation",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending (Partial Payment)"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="jamath.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "membership_portion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount towards membership fee",
                        max_digits=10,
                    ),
                ),
                (
                    "donation_portion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Voluntary extra as Sadaqah",
                        max_digits=10,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="jamath.subscription",
                    ),
                ),
            ],
        ),
    ]
