# Generated by Django 5.2.9 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0003_announcement_fundraising_target_announcement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current amount raised toward the target', max_digits=12),
        ),
    ]
