# Generated by Django 5.2.9 on 2026-04-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0004_announcement_amount_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='amount_raised',
        ),
    ]
