# Generated by Django 5.2.9 on 2025-12-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0004_membershipconfig_household_housing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="membership_id_prefix",
            field=models.CharField(
                default="JM-",
                help_text="Prefix for auto-generated membership IDs",
                max_length=10,
            ),
        ),
    ]
