# Generated by Django 5.2.9 on 2025-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0005_membershipconfig_membership_id_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="household_label",
            field=models.CharField(
                default="Gharane",
                help_text="Display label for households (e.g., Gharane, Families, Khandan)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="masjid_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for the masjid",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="member_label",
            field=models.CharField(
                default="Afrad",
                help_text="Display label for members (e.g., Afrad, Members)",
                max_length=50,
            ),
        ),
    ]
