# Generated by Django 5.2.9 on 2026-04-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0005_remove_announcement_amount_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipconfig',
            name='is_strict_accounting',
            field=models.BooleanField(default=True, help_text='Enforce strict balance checks and double-entry validations'),
        ),
    ]
