# Generated by Django 5.2.9 on 2026-02-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0015_telegram_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_household',
            field=models.ForeignKey(blank=True, help_text='If set, this announcement is visible ONLY to this household.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='jamath.household'),
        ),
    ]
