# Generated by Django 5.2.9 on 2026-02-05 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0016_announcement_target_household'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Override role permissions if set'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='designation',
            field=models.CharField(blank=True, help_text="Official title, e.g. 'General Secretary'", max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='jamath.staffrole'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
