# Generated by Django 5.2.9 on 2026-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0017_alter_staffmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='fund_type',
            field=models.CharField(blank=True, help_text='Required for Income/Expense accounts', max_length=50, null=True),
        ),
    ]
