# Generated by Django 5.2.9 on 2026-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0018_alter_ledger_fund_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('ZAKAT', 'Restricted - Zakat'), ('SADAQAH', 'Restricted - Sadaqah'), ('CONSTRUCTION', 'Restricted - Construction'), ('GENERAL', 'Unrestricted - General')], help_text='Required for Income/Expense accounts', max_length=20, null=True),
        ),
    ]
