# Generated by Django 5.2.9 on 2026-02-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamath', '0020_dataagentchatlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramLink',
        ),
        migrations.RemoveField(
            model_name='membershipconfig',
            name='telegram_auto_reminders',
        ),
        migrations.RemoveField(
            model_name='membershipconfig',
            name='telegram_enabled',
        ),
        migrations.RemoveField(
            model_name='membershipconfig',
            name='telegram_notify_announcements',
        ),
        migrations.RemoveField(
            model_name='membershipconfig',
            name='telegram_notify_profile_updates',
        ),
    ]
